apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  selector:
    matchLabels:
      app: inventory-app
  replicas: 5
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
      - name: inventory-app
        image: inventory/app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000