apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: inventory-app
  name: inventory-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: inventory-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: inventory-app
    spec:
      containers:
      - image: rangeenameenu/inventory-app:{{tag}}
        imagePullPolicy: Always
        name: inventory-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
